### ISSUE TITLE
Problem with load.py

### ISSUE THREAD

**Issue by Karmans1** [yihui-he/GAN-MNIST#5]
I apologize if its a basic question, I'm new to Tensorflow. When I run train.py I get the following error while loading the MNIST dataset:

Traceback (most recent call last):
  File "/home/m132/Desktop/Python/Learning GANs/GAN-MNIST-DC/train.py", line 19, in <module>
    trX, vaX, teX, trY, vaY, teY = mnist_with_valid_set()
  File "/home/m132/Desktop/Python/Learning GANs/GAN-MNIST-DC/Load_Data.py", line 31, in mnist_with_valid_set
    trX, teX, trY, teY = mnist()
  File "/home/m132/Desktop/Python/Learning GANs/GAN-MNIST-DC/Load_Data.py", line 11, in mnist
    trX = loaded[16:].reshape((60000,28*28)).astype(float)
ValueError: cannot reshape array of size 9912406 into shape (60000,784)

Any help would be appreciated.

**Comment by wangtianrui** [comment]
you can use  input_data.py (demo) to load
